### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by NicoHood**
Ready for testing.

### CODE REVIEW

**Comment by NicoHood** [comment]
@WoLpH would you mind trying this new GPGit release? I reverted back to a bash script as it is simpler and better to handle like that. Especially with dependencies. The new version should be faster to install and use while still being user friendly. Opinions appreciated.

**Comment by WoLpH** [comment]
I've been working on it for several hours and trying to get it to work but there are a lot of differences between Linux and OS X/BSD here.

1. The install command has different parameters
2. The getopt has different parameters
3. `/bin/bash` doesn't exist and/or is a severely limited shell and should be replaced with something like `/usr/bin/env bash`
4. The `sha512sum` commands don't exist and need to be replaced with either `gsha512sum` or `shasum -a 512`

I'll keep working on it for a bit to see if I can get it working somehow

**Comment by NicoHood** [comment]
Thanks for the feedback. It would be nice to get it also working on BSD. I am not using it though.

**Comment by WoLpH** [comment]
Perhaps a simple self-check is in order, Travis can do the actual OS checking in that case :)

**Pull request merged**
